language: node_js
node_js:
  - '6.3.0'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    - node_modules
branches:
  only: [master]
